### ISSUE TITLE
$response must be check for NULL value

### ISSUE THREAD

**Issue by egorsmkv** [DavidePastore/ipinfo#12]
https://github.com/DavidePastore/ipinfo/blob/master/src/DavidePastore/Ipinfo/Ipinfo.php#L202

**Comment by DavidePastore** [comment]
Hi @egorsmkv . Thanks for your suggestion. I'll try to fix it ASAP but if you already fixed it, you could create a PR. :ice_cream:

**Comment by egorsmkv** [comment]
@DavidePastore Sorry, but I don't fixed it.

**Comment by DavidePastore** [comment]
@egorsmkv Can you please check if https://github.com/DavidePastore/ipinfo/issues/17 solves your issue? Thanks

**Comment by egorsmkv** [comment]
@DavidePastore Having looked at the code, I think that the problem is solved.

**Comment by DavidePastore** [comment]
@egorsmkv Thanks for your feedback. Just released v0.1.3 version with this fix and [more](https://github.com/DavidePastore/ipinfo/releases/tag/v0.1.3).

**Comment by egorsmkv** [comment]
@DavidePastore your welcome. I will update mu software later.
