### ISSUE TITLE
String response is not handled properly

### ISSUE THREAD

**Issue by vharish** [DavidePastore/ipinfo#22]
https://github.com/DavidePastore/ipinfo/blob/5f3cf0751bca1ffdd2323af5c3e53e763dbc36f3/src/DavidePastore/Ipinfo/Ipinfo.php#L136

In case there is a string response from ipinfo, the json decoding function returns a `NULL`. This in turn fails in the `Host.php` constructor.

**Scenario**: When subscription has expired. The below response is received,
```Rate limit exceeded. Subscribe to a paid plan to increase your usage limits at http://ipinfo.io/pricing, or contact us via http://ipinfo.io/contact```

As explained above, this fails as array_merge in the `Host.php` constructor is called with a `NULL` input.

**Comment by DavidePastore** [comment]
Hi @vharish, I'm working on a fix on this.

**Comment by DavidePastore** [comment]
@vharish Just released v0.2.0 version with this fix and more.
