### ISSUE TITLE
Update installation docs

### ISSUE THREAD

**Issue by rvalitov** [DavidePastore/ipinfo#37]
May be it's better to change the way the lib is installed, and do it like this, so it's safe to use the latest release of the same major version:

```js
"require" : {
	"davidepastore/ipinfo" : "^0.3.*"
}
```

**Comment by DavidePastore** [comment]
@rvalitov Nice catch. Can you please create a PR about this? Thanks 😄

**Comment by rvalitov** [comment]
Sure, I will.
