### ISSUE TITLE
results are null

### ISSUE THREAD

**Issue by kicha16** [DavidePastore/ipinfo#49]
Why my results are null from the $host variable

The code i have used is:

require __DIR__ . '/vendor/autoload.php';

  $ipInfo = new DavidePastore\Ipinfo\Ipinfo(array(
    "token" => "XXXXXXXXXXX",
    "curlOptions" => array(
              CURLOPT_CONNECTTIMEOUT => 1,
              CURLOPT_TIMEOUT => 2,
              CURLOPT_CAINFO => __DIR__ . "/cacert.pem"
      )
  ));

  try {
    $host = $ipInfo->getFullIpDetails("8.8.8.8");
    print_r($host)
  } catch (IpInfoExceptionException $e) {
    echo 'Caught exception: ',  $e->getMessage(), "\n";
  }

My result is:
DavidePastore\Ipinfo\Host Object ( [properties:protected] => Array ( [city] => [country] => [hostname] => [ip] => [loc] => [org] => [phone] => [postal] => [region] => ) )

**Comment by DavidePastore** [comment]
Hi @kicha16 . Thanks for reporting this issue. First, are you sure that the token you're using is valid?

**Comment by marcoM32** [comment]
I have same issue,  with out internet cinnection the response is full of null values and no exception is throw. In my case che client it is set without token.

**Comment by DavidePastore** [comment]
This issue should be fixed in version 0.6.0. Feel free to open a new one if you still face problems.
