### ISSUE TITLE
adding a license

### ISSUE THREAD

**Issue by paper-michael** [DavidePastore/ipinfo#55]
hello!

I would like to use this package but there doesn't seem to be any license for how it can be used. Is there a chance you could add one?

https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

**Comment by paper-michael** [comment]
closing as we were able to just remove the package from our repo entirely.

**Comment by DavidePastore** [comment]
Thank you for reporting this issue. It was fixed by #60.
